### ISSUE TITLE
Background 

### ISSUE THREAD

**Issue by goug0035** [goug0035/portfolio#1]
I don't understand why my background image isn't showing.

@ericadamski

**Comment by ericadamski** [comment]
I am assuming you mean this line here 
`background: url(images/mary.jpg) no-repeat center center fixed;`

if so, it should look something like `... url('../images/mary.jpg') ...`

**Comment by goug0035** [comment]
It's still not working and I changed it :(

**Comment by ericadamski** [comment]
Check again, you have a typo

**Comment by goug0035** [comment]
yay :)  got it

 thank you
